@startuml  Pacotes

Api.ImportaNF.NFController -- ReceitaFederalApi

Api.ImportaNF.NFController -- Api.ImportaNF.NotaFiscal

Api.Convenio.Faturamento -- Api.Convenio.Lote
Api.Convenio.Lote -- Api.Convenio.Procedimento
Api.Convenio.ConvenioController -- Api.Convenio.Procedimento

Api.Usuario -- Api.MenuController

Api.MenuController -- Api.Convenio.ConvenioController
Api.MenuController -- Api.ImportaNF.NFController
Api.MenuController -- Api.Prescricao_Medica.Prescricao_Controller
Api.MenuController -- Api.Pedido_Compra.Pedido_Compra_Controller
Api.MenuController -- Api.Transacoes_Pagamento.Transacoes_Controller


Api.log -- Api.ImportaNF.NFController
Api.log -- Api.Transacoes_Pagamento.Transacoes_Controller

Api.Pedido_Compra.Pedido_Compra_Controller -- Api.Pedido_Compra.Pedido_Compra
Api.Pedido_Compra.Pedido_Compra -- Api.Pedido_Compra.ItemPedido
Api.Pedido_Compra.ItemPedido -- Api.Pedido_Compra.Produto

Api.Transacoes_Pagamento.Transacoes_Controller -- Api.Transacoes_Pagamento.Transacoes

Api.Prescricao_Medica.Prescricao_Controller -- Api.Prescricao_Medica.Prescricao




package Api{

package Usuario{
}

package MenuController{
}

package log{
}

package Prescricao_Medica{

    package Prescricao_Controller{
    }

    package Prescricao{
    }

}

package Pedido_Compra{
    package Pedido_Compra_Controller{
    }

    package Produto{
    }

    package ItemPedido{
    }

    package Pedido_Compra{
    }
}


package Transacoes_Pagamento{
    package Transacoes_Controller{
    }

    package Transacoes{

    }
}

package Convenio{

    package ConvenioController{   
    }

    package Procedimento{
    }

    package Lote{
    }

    package Faturamento{
    }

}


package ImportaNF{

package NotaFiscal {
}

package NFController{
}

}

}


package ReceitaFederalApi{
}

@enduml